config/routes.rb
EndangeredPetsSample::Application.routes.draw do
  scope(path: "pets", controller: :pets, as: :pets) do
    match :buy
    get :transparent_redirect_complete
    get :successful_purchase
    get :successful_delayed_purchase
    get :offsite_redirect
    post :offsite_callback
  end

  scope(path: "pet_club", controller: :pet_club, as: :pet_club) do
    match :subscribe
    get :transparent_redirect_complete
    get :successful_delayed_authorize
    get :successful_delayed_purchase
    get :offsite_authorize_redirect
    post :offsite_callback
  end

  get  'admin' => 'admin#index'
  post 'admin/payment_methods/:token/initate_charge' => 'pet_club#initiate_charge', as: :initiate_charge
  post 'admin/payment_methods/remove' => 'pet_club#remove_payment_methods', as: :remove_payment_methods
  resources :orders, only: [ :index ] do
    collection do
      post :settle
    end
  end

  get 'about' => "home#about"
  root to: "home#index"
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  include PaymentsController

  def buy
    @payment_method = PaymentMethod.new
    @paying_with_credit_card = false
  end

  def transparent_redirect_complete
    return if error_talking_to_core

    @payment_method = PaymentMethod.new_from_core_response(SpreedlyCore.get_payment_method(params[:token]))
    @paying_with_credit_card = @payment_method.payment_method_type == 'credit_card'
    return render(action: :buy) unless @payment_method.valid?

    order = Order.create_pets_order!(@payment_method)
    response = SpreedlyCore.purchase(@payment_method, order.amount, order_id: order.id, redirect_url: pets_offsite_redirect_url, callback_url: pets_offsite_callback_url)
    order.update_from(response)

    case response.code
    when 200
      return redirect_to(pets_successful_purchase_url)
    when 202
      return redirect_to(Transaction.new(response).checkout_url)
    else
      set_flash_error(response)
      render(action: :buy)
    end
  end

  def successful_purchase
  end

  def successful_delayed_purchase
  end

  def offsite_redirect
    return if error_talking_to_core

    @transaction = Transaction.new(SpreedlyCore.get_transaction(params[:transaction_token]))
    @transaction.update_order
    @payment_method = @transaction.payment_method

    case @transaction.state
    when "succeeded"
      redirect_to pets_successful_purchase_url
    when "processing"
      redirect_to pets_successful_delayed_purchase_url
    when "gateway_processing_failed"
      flash.now[:error] = @transaction.message
      render :buy
    else
      raise "Unknown state #{@transaction.state}"
    end
  end

  private
  def render_action_for_error_talking_to_core
    :buy
  end
end

app/views/pets/_credit_card_fields.html.erb
<div id="credit_card_form" class="<%= @paying_with_credit_card ? nil : 'hidden' %>">
  <%= fields_for @payment_method.credit_card, as: :credit_card do |f| %>
    <div class="row-fluid">
      <div class="span3">
        <%= f.label :full_name, "Name" %>
        <%= f.text_field :full_name, class: "span12" %>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span3">
        <%= f.label :number, "Card Number" %>
        <%= f.text_field :number, autocomplete: "off", class: "span12" %>
      </div>

      <div class="span2">
        <%= f.label :verification_value, "CVV" %>
        <%= f.text_field :verification_value, autocomplete: "off", class: "span12" %>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span3">
        <%= f.label :month, "Expiration" %>
        <%= f.text_field :month, placeholder: "Month", class: "span12" %>
      </div>
      <div class="span2">
        <%= f.label :year, "&nbsp;".html_safe %>
        <%= f.text_field :year, placeholder: "Year", class: "span12" %>
      </div>
    </div>

    <br/>
    <button type="submit" class="btn btn-primary" id="revealed_pay_with_card_button">Purchase</button>
  <% end %>

  <div>
    <br/>
    <br/>
    <p>
      * This is hooked up to a Spreedly Test gateway and does not use real money.
      <br/>
      &nbsp; This gateway accepts a <%= link_to 'number of test cards', 'https://docs.spreedly.com/reference/test-data/' %>.  Here are a few examples:
    </p>

    <table class="table span6">
      <tr>
        <th>Card Type</th>
        <th>Good Card</th>
        <th>Declined/Failed Card</th>
      </tr>
      <td>Visa</td>
      <td>4111111111111111</td>
      <td>4012888888881881</td>
      <tr>
        <td>MasterCard</td>
        <td>5555555555554444</td>
        <td>5105105105105100</td>
      </tr>
    </table>


  </div>

</div>

app/views/pets/_hidden_form_fields.html.erb
<%= hidden_field_tag :redirect_url, pets_transparent_redirect_complete_url %>
<%= hidden_field_tag :environment_key, SpreedlyCore.environment_key %>
<%= hidden_field_tag :payment_method_token, @payment_method.token %>

app/views/pets/_how_many.html.erb
<div class="row-fluid">
  <div class="span3">
    <%= f.text_field :how_many, placeholder: "Number of pets", class: "span12" %>
    <br/>
    <br/>
  </div>
</div>

app/views/pets/_payment_methods.html.erb
<div id="other_payment_method_buttons" class="<%= @paying_with_credit_card ? 'hidden' : nil %>">
  <div class="row-fluid">
    <div class="span8">
      <%= link_to "Pay via Credit Card", '#', id: "original_pay_with_card_button", class: "btn span4 #{@paying_with_credit_card ? 'hidden' : nil}" %>
      <button type="submit" class="btn span4" name="payment_method_type" value="sprel">Pay via Sprel</button>
      <br/>
    </div>
  </div>

  <br/>

  <div class="row-fluid">
    <div class="span8">
      <button type="submit" class="btn span4" name="payment_method_type" value="paypal">Pay via Paypal</button>
      <button type="submit" class="btn span4" name="payment_method_type" value="dwolla">Pay via Dwolla</button>
    </div>
  </div>

  <br/>
  <br/>
  <br/>
  <div>
    <p>
      * Credit Card and Sprel are hooked up to test accounts.
    </p>
    <p>
      * Paypal and Dwolla are hooked up to <strong>real accounts</strong> using real money.
    </p>
  </div>
</div>

app/views/pets/buy.html.erb
<div class="container">
  <div class="page-header">
    <h1>Buy Endangered Pets</h1>
    <h2>
      <small>For only 2 cents a piece!</small>
    </h2>

  </div>

  <%= form_for @payment_method, as: :data, url: SpreedlyCore.add_payment_method_url do |f| %>
    <%= error_messages_for object: [ @payment_method, @payment_method.credit_card ] %>
    <%= render 'pets/hidden_form_fields' %>

    <div class="row-fluid">
      <div class="span8">
        <%= render 'pets/how_many', f: f %>
        <%= render "pets/credit_card_fields" %>
        <%= render "pets/payment_methods" %>
      </div>
    </div>

  <% end %>

</div>

app/views/pets/subscribe.html.erb
<div class="container">
  <div class="page-header">
    <h1>Endangered Pet of the Month Club</h1>
    <h2>
      <small>
        <p>
          You can easily sign up to receive one cute and cuddly pet every month.
        </p>
        <p>
          For only $1.09/month, we'll hand-deliver a new pet with special care and feeding instructions.
        </p>
      </small>
    </h2>

  </div>

  <%= form_for @payment_method, as: :data, url: SpreedlyCore.add_payment_method_url do |f| %>
    <%= error_messages_for object: [ @payment_method ] %>
    <div class="set">
      <%= hidden_field_tag :environment_key, SpreedlyCore.environment_key %>
      <%= hidden_field_tag :redirect_url, pets_transparent_redirect_complete_url %>
      <%= hidden_field_tag 'gocardless[interval_length]', "1" %>
      <%= hidden_field_tag 'gocardless[interval_unit]', "month" %>
      <%= hidden_field_tag 'gocardless[name]', "Monthly Extinct Pet" %>
      <%= hidden_field_tag 'gocardless[description]', "Receive one cute cuddly pet every month" %>

      <%= text_field_tag :email, params[:email], placeholder: "Your Email Address" %>

      <br/><br/>
      <button type="submit" class="btn" name="payment_method_type" value="sprel">Pay via Sprel</button>
      <button type="submit" class="btn" name="payment_method_type" value="gocardless">Pay via GoCardless</button>
      <button type="submit" class="btn" name="payment_method_type" value="paypal">Pay via PayPal</button>

    </div>
  <% end -%>

  <br/>
  <br/>
  <br/>
  <div>
    <p>
      * Sprel is a payment method only used by the Spreedly Test gateway.  No funds are really transferred.
    </p>
    <p>
      * GoCardless and Paypal are hooked up to <strong>real accounts</strong> using real money.
    </p>
  </div>

</div>

app/views/pets/successful_delayed_purchase.html.erb
<div class="container">
  <div class="page-header">
    <h1>Whooo Hooo!</h1>
    <h2>
      <small>
        <p>You have successfully made a purchase.  Well done!</p>
        <p>The funds will be withdrawn from your account soon.</p>
      </small>
    </h2>
  </div>

  <p class="lead">
    <%= link_to "Buy more stuff!", root_url %>
  </p>

</div>

app/views/pets/successful_purchase.html.erb
<div class="container">
  <div class="page-header">
    <h1>Whooo Hooo!</h1>
    <h2>
      <small>You have successfully made a purchase.  Well done!</small>
    </h2>
  </div>

  <p class="lead">
    <%= link_to "Buy more stuff!", root_url %>
  </p>

</div>