config/routes.rb
EndangeredPetsSample::Application.routes.draw do
  scope(path: "pets", controller: :pets, as: :pets) do
    match :buy
    get :transparent_redirect_complete
    get :successful_purchase
    get :successful_delayed_purchase
    get :offsite_redirect
    post :offsite_callback
  end

  scope(path: "pet_club", controller: :pet_club, as: :pet_club) do
    match :subscribe
    get :transparent_redirect_complete
    get :successful_delayed_authorize
    get :successful_delayed_purchase
    get :offsite_authorize_redirect
    post :offsite_callback
  end

  get  'admin' => 'admin#index'
  post 'admin/payment_methods/:token/initate_charge' => 'pet_club#initiate_charge', as: :initiate_charge
  post 'admin/payment_methods/remove' => 'pet_club#remove_payment_methods', as: :remove_payment_methods
  resources :orders, only: [ :index ] do
    collection do
      post :settle
    end
  end

  get 'about' => "home#about"
  root to: "home#index"
end

app/controllers/pet_club_controller.rb
class PetClubController < ApplicationController

  include PaymentsController

  def subscribe

  end

  def transparent_redirect_complete
    return if error_talking_to_core

    @payment_method = PaymentMethod.new_from_core_response(SpreedlyCore.get_payment_method(params[:token]))
    @payment_method.recurring = true

    return render(action: :subscribe) unless @payment_method.valid?

    response = SpreedlyCore.authorize(@payment_method, amount_to_authorize, redirect_url: pet_club_offsite_authorize_redirect_url,
                                      callback_url: pet_club_offsite_callback_url, description: "Endangered Pet Subscription",
                                      retain_on_success: true)

    case response.code
    when 202
      return redirect_to(Transaction.new(response).checkout_url)
    else
      set_flash_error(response)
      render(action: :subscribe)
    end
  end

  def initiate_charge
    @payment_method = PaymentMethod.find_by_token!(params[:token])

    order = Order.create_pet_club_charge_order!(@payment_method)
    response = SpreedlyCore.purchase(@payment_method, order.amount, callback_url: pet_club_offsite_callback_url, order_id: order.id)
    order.update_from(response)

    case response.code
    when 202, 200
      transaction = Transaction.new(response)
      message = "Charge successful."
      message += "  The funds will be transferred soon." if transaction.state == "processing"
      return redirect_to admin_url, notice: message
    else
      set_flash_error(response)
      @payment_methods = PaymentMethod.recurring.order('created_at DESC')
      render(template: 'admin/index')
    end
  end

  def remove_payment_methods
    PaymentMethod.destroy_all
    redirect_to admin_url, notice: "Removed payment methods"
  end

  def offsite_authorize_redirect
    return if error_talking_to_core

    @transaction = Transaction.new(SpreedlyCore.get_transaction(params[:transaction_token]))
    @payment_method = @transaction.payment_method

    case @transaction.state
    when "processing", "succeeded"
      @payment_method.save!
      redirect_to pet_club_successful_delayed_authorize_url
    when "gateway_processing_failed"
      flash.now[:error] = @transaction.message
      render :subscribe
    else
      raise "Unknown state #{@transaction.state}"
    end
  end

  def successful_delayed_authorize
  end

  def successful_delayed_purchase
  end


  private
  def amount_to_authorize
    109
  end

  def render_action_for_error_talking_to_core
    :subscribe
  end

end

app/views/pet_club/subscribe.html.erb
<div class="container">
  <div class="page-header">
    <h1>Endangered Pet of the Month Club</h1>
    <h2>
      <small>
        <p>
          You can easily sign up to receive one cute and cuddly pet every month.
        </p>
        <p>
          For only $1.09/month, we'll hand-deliver a new pet with special care and feeding instructions.
        </p>
      </small>
    </h2>

  </div>

  <%= form_for @payment_method, as: :data, url: SpreedlyCore.add_payment_method_url do |f| %>
    <%= error_messages_for object: [ @payment_method ] %>
    <div class="set">
      <%= hidden_field_tag :environment_key, SpreedlyCore.environment_key %>
      <%= hidden_field_tag :redirect_url, pet_club_transparent_redirect_complete_url %>
      <%= hidden_field_tag 'gocardless[interval_length]', "1" %>
      <%= hidden_field_tag 'gocardless[interval_unit]', "month" %>
      <%= hidden_field_tag 'gocardless[name]', "Monthly Extinct Pet" %>
      <%= hidden_field_tag 'gocardless[description]', "Receive one cute cuddly pet every month" %>

      <%= text_field_tag :email, params[:email], placeholder: "Your Email Address" %>

      <br/><br/>
      <button type="submit" class="btn" name="payment_method_type" value="sprel">Pay via Sprel</button>
      <button type="submit" class="btn" name="payment_method_type" value="paypal">Pay via PayPal</button>

    </div>
  <% end -%>

  <br/>
  <br/>
  <br/>
  <div>
    <p>
      * Sprel is a payment method only used by the Spreedly Test gateway.  No funds are really transferred.
    </p>
    <p>
      * Paypal is hooked up to a <strong>real account</strong> using real money.
    </p>
  </div>

</div>

app/views/pet_club/successful_delayed_authorize.html.erb
<div class="container">
  <div class="page-header">
    <h1>Whooo Hooo!</h1>
    <h2>
      <small>
        <p>You have successfully authorized us to charge you.  Well done!</p>
        <p>We'll charge you the first time once we start packaging up the first pet.</p>
      </small>
    </h2>
  </div>

  <p class="lead">
    <%= link_to "Buy more stuff!", root_url %>
  </p>

</div>

app/views/pet_club/successful_delayed_purchase.html.erb
<div class="container">
  <div class="page-header">
    <h1>Whooo Hooo!</h1>
    <h2>
      <small>The purchase successfully went through.  The funds will be transferred soon.</small>
    </h2>
  </div>

  <p class="lead">
    <%= link_to "Home", root_url %>
  </p>

</div>