config/routes.rb
EndangeredPetsSample::Application.routes.draw do
  scope(path: "pets", controller: :pets, as: :pets) do
    match :buy
    get :transparent_redirect_complete
    get :successful_purchase
    get :successful_delayed_purchase
    get :offsite_redirect
    post :offsite_callback
  end

  scope(path: "pet_club", controller: :pet_club, as: :pet_club) do
    match :subscribe
    get :transparent_redirect_complete
    get :successful_delayed_authorize
    get :successful_delayed_purchase
    get :offsite_authorize_redirect
    post :offsite_callback
  end

  get  'admin' => 'admin#index'
  post 'admin/payment_methods/:token/initate_charge' => 'pet_club#initiate_charge', as: :initiate_charge
  post 'admin/payment_methods/remove' => 'pet_club#remove_payment_methods', as: :remove_payment_methods
  resources :orders, only: [ :index ] do
    collection do
      post :settle
    end
  end

  get 'about' => "home#about"
  root to: "home#index"
end

app/helpers/layout_helper.rb
module LayoutHelper

  def flash_value
    flash.collect do |key, value|
      %{<div class="alert alert-#{key}">#{value}</div>}
    end.join("\n").html_safe
  end

end

app/views/layouts/_flash_details.html.erb
<% unless flash.empty? %>
  <div id="flash">
    <%= flash_value %>
  </div>
  <% if @error %>
    <div class="error">
      <%= raw(@error) %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_messages.html.erb
<% unless flash.empty? %>
  <div class="container">
    <%= flash_value %>
  </div>
  <% if @error %>
    <div class="error">
      <%= raw(@error) %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= APP_NAME %></title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag 'application' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <a href="/" class="brand">Home</a>
          <ul class="nav">
            <li>
              <%= link_to "Buy Pets", pets_buy_url %>
            </li>
            <li>
              <%= link_to "Pet Club", pet_club_subscribe_url %>
            </li>
            <li>
              <%= link_to "Orders", orders_url %>
            </li>
            <li>
              <%= link_to "Admin", admin_url %>
            </li>
            <li>
              <%= link_to "About", about_url %>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <%= render '/layouts/messages' %>
    <%= yield %>
    <div class="container">
      <hr/>
      <footer>
        <p>
          <%= image_tag 'umbrella.png', width: '55' %>
          <small>
            © 2016 <%= link_to "Spreedly", "https://spreedly.com" %> Inc.  All rights reserved.
          </small>
        </p>
      </footer>
    </div>
  </body>
</html>